apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: mlflow
  name: mlflow-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: mlflow-pv
